# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 442)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/e2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pantalla = QtWidgets.QTabWidget(Form)
        self.pantalla.setGeometry(QtCore.QRect(0, 0, 601, 451))
        self.pantalla.setStyleSheet("background-color: rgb(135, 135, 163);\n"
"QTabBar::tab {\n"
"    background-color: rgb(135, 135, 163);\n"
"}")
        self.pantalla.setObjectName("pantalla")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabla_productos = QtWidgets.QTableWidget(self.tab)
        self.tabla_productos.setGeometry(QtCore.QRect(50, 80, 501, 291))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabla_productos.setFont(font)
        self.tabla_productos.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"    color: #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #646464;\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}")
        self.tabla_productos.setObjectName("tabla_productos")
        self.tabla_productos.setColumnCount(5)
        self.tabla_productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(4, item)
        self.bt_refrescar = QtWidgets.QPushButton(self.tab)
        self.bt_refrescar.setGeometry(QtCore.QRect(250, 380, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bt_refrescar.setFont(font)
        self.bt_refrescar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_refrescar.setStyleSheet("background-color: rgb(2, 230, 47);\n"
"border: 2px solid green;\n"
"selection-background-color: rgb(170, 255, 127);\n"
"border-radius: 10px;\n"
"color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_refrescar.setIcon(icon1)
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pantalla.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabla_buscar = QtWidgets.QTableWidget(self.tab_2)
        self.tabla_buscar.setGeometry(QtCore.QRect(50, 110, 501, 291))
        self.tabla_buscar.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"    color: #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #646464;\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}")
        self.tabla_buscar.setObjectName("tabla_buscar")
        self.tabla_buscar.setColumnCount(5)
        self.tabla_buscar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar.setHorizontalHeaderItem(4, item)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 501, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.codigoB = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.codigoB.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.codigoB.setObjectName("codigoB")
        self.horizontalLayout_6.addWidget(self.codigoB)
        self.bt_buscar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bt_buscar.setFont(font)
        self.bt_buscar.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 2px solid yellow;\n"
"border-radius: 10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_buscar.setIcon(icon2)
        self.bt_buscar.setObjectName("bt_buscar")
        self.horizontalLayout_6.addWidget(self.bt_buscar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.pantalla.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_agregar = QtWidgets.QPushButton(self.tab_3)
        self.bt_agregar.setGeometry(QtCore.QRect(250, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bt_agregar.setFont(font)
        self.bt_agregar.setStyleSheet("background-color: rgb(40, 19, 148);\n"
"border: rgb(85, 85, 255);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"border-radius: 10px;\n"
"color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_agregar.setIcon(icon3)
        self.bt_agregar.setObjectName("bt_agregar")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 90, 321, 211))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nombreA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nombreA.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.nombreA.setObjectName("nombreA")
        self.verticalLayout_2.addWidget(self.nombreA)
        self.modeloA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.modeloA.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.modeloA.setObjectName("modeloA")
        self.verticalLayout_2.addWidget(self.modeloA)
        self.precioA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.precioA.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.precioA.setObjectName("precioA")
        self.verticalLayout_2.addWidget(self.precioA)
        self.cantidadA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.cantidadA.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.cantidadA.setObjectName("cantidadA")
        self.verticalLayout_2.addWidget(self.cantidadA)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(50, 30, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.pantalla.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 20, 160, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.id_producto = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.id_producto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.id_producto.setObjectName("id_producto")
        self.verticalLayout_4.addWidget(self.id_producto)
        self.id_buscar = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.id_buscar.setFont(font)
        self.id_buscar.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 2px solid yellow;\n"
"border-radius: 10px;")
        self.id_buscar.setIcon(icon2)
        self.id_buscar.setObjectName("id_buscar")
        self.verticalLayout_4.addWidget(self.id_buscar)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 140, 271, 251))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.nombre_actualizar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.nombre_actualizar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.nombre_actualizar.setObjectName("nombre_actualizar")
        self.verticalLayout_6.addWidget(self.nombre_actualizar)
        self.modelo_actualizar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.modelo_actualizar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.modelo_actualizar.setObjectName("modelo_actualizar")
        self.verticalLayout_6.addWidget(self.modelo_actualizar)
        self.precio_actualizar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.precio_actualizar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.precio_actualizar.setObjectName("precio_actualizar")
        self.verticalLayout_6.addWidget(self.precio_actualizar)
        self.cantidad_actualizar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.cantidad_actualizar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.cantidad_actualizar.setObjectName("cantidad_actualizar")
        self.verticalLayout_6.addWidget(self.cantidad_actualizar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.bt_actualizar = QtWidgets.QPushButton(self.tab_4)
        self.bt_actualizar.setGeometry(QtCore.QRect(420, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bt_actualizar.setFont(font)
        self.bt_actualizar.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"border: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_actualizar.setIcon(icon4)
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.pantalla.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabla_borrar = QtWidgets.QTableWidget(self.tab_5)
        self.tabla_borrar.setGeometry(QtCore.QRect(50, 80, 501, 291))
        self.tabla_borrar.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"    color: #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #646464;\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}\n"
"")
        self.tabla_borrar.setObjectName("tabla_borrar")
        self.tabla_borrar.setColumnCount(5)
        self.tabla_borrar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 0, 261, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.codigo_borrar = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.codigo_borrar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #A8A8A8; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.codigo_borrar.setObjectName("codigo_borrar")
        self.horizontalLayout_3.addWidget(self.codigo_borrar)
        self.bt_borrar = QtWidgets.QPushButton(self.tab_5)
        self.bt_borrar.setGeometry(QtCore.QRect(260, 380, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.bt_borrar.setFont(font)
        self.bt_borrar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid red;\n"
"border-radius: 10px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Manejo de archivos/icono/x-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_borrar.setIcon(icon5)
        self.bt_borrar.setObjectName("bt_borrar")
        self.borrar_ok = QtWidgets.QPushButton(self.tab_5)
        self.borrar_ok.setGeometry(QtCore.QRect(450, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.borrar_ok.setFont(font)
        self.borrar_ok.setStyleSheet("background-color:rgb(76, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.borrar_ok.setObjectName("borrar_ok")
        self.pantalla.addTab(self.tab_5, "")

        self.retranslateUi(Form)
        self.pantalla.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Registro de Catalogo"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Modelo"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_productos.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Cantidad"))
        self.bt_refrescar.setText(_translate("Form", "Refrescar"))
        self.label_4.setText(_translate("Form", "Mostrar los productos registrados usando el botón refrescar:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab), _translate("Form", "Productos"))
        item = self.tabla_buscar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tabla_buscar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tabla_buscar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Modelo"))
        item = self.tabla_buscar.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_buscar.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Cantidad"))
        self.label_8.setText(_translate("Form", "Busque el producto mediante su nombre:"))
        self.label.setText(_translate("Form", "NOMBRE:"))
        self.bt_buscar.setText(_translate("Form", "Buscar"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_2), _translate("Form", "Buscar producto"))
        self.bt_agregar.setText(_translate("Form", "Agregar"))
        self.label_3.setText(_translate("Form", "Nombre:"))
        self.label_2.setText(_translate("Form", "Modelo:"))
        self.label_5.setText(_translate("Form", "Precio:"))
        self.label_6.setText(_translate("Form", "Cantidad:"))
        self.label_14.setText(_translate("Form", "Agregue un producto ingresando sus atributos:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_3), _translate("Form", "Agregar nuevo producto"))
        self.label_7.setText(_translate("Form", "Ingrese el ID del producto:"))
        self.id_buscar.setText(_translate("Form", "Buscar"))
        self.label_9.setText(_translate("Form", "Nombre:"))
        self.label_10.setText(_translate("Form", "Modelo:"))
        self.label_11.setText(_translate("Form", "Precio:"))
        self.label_12.setText(_translate("Form", "Cantidad:"))
        self.bt_actualizar.setText(_translate("Form", "Actualizar"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_4), _translate("Form", "Actualizar producto"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Modelo"))
        item = self.tabla_borrar.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_borrar.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Cantidad"))
        self.label_13.setText(_translate("Form", "NOMBRE:"))
        self.bt_borrar.setText(_translate("Form", "Borrar"))
        self.borrar_ok.setText(_translate("Form", "OK"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_5), _translate("Form", "Borrar producto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
